name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Force accept Android licenses
      run: |
        mkdir -p ~/.android
        echo "### User Sources for Android SDK Manager" > ~/.android/repositories.cfg
        echo "count=0" >> ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk
        pip3 install buildozer cython
        
    - name: Build APK
      run: |
        buildozer -v android debug
      timeout-minutes: 60
